# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:git

stages:
- build
- test
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
  - docker:dind

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $LEMUR >> ~/.ssh/known_hosts

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
test:
  stage: test
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
    - docker run "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" WIT_CLIENT_KEY=test swagger project test
release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
deploy_staging:
  stage: deploy
  script:
    - git push dokku@$LEMUR:talk master
  environment:
    name: lemur
    url: http://talk.dokku.lemur
  only:
  - master
