swagger: '2.0'
info:
  version: '0'
  title: wonowo-talk
  description: API booking holidays with nlp intagration
host: localhost:5000
basePath: /api/v0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /recomendations:
    x-swagger-router-controller: nlp
    post:
      operationId: POST_recomendations
      summary: recomendations
      tags:
        - nlp
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              text:
                type: string
              locale:
                type: string
              date:
                type: string
              timezone:
                type: string
              initCity:
                type: string
            required:
              - text
              - initCity
              - date
            example:
              text: ir de vacaciones con Claudia a Barcelona
              locale: en-US
              date: '2016-11-27T11:40:25.677Z'
              timezone: Europe/Zurich
              initCity: Madrid
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              personas:
                type: number
              destination:
                type: string
              dates:
                type: array
                items:
                  $ref: '#/definitions/date'
        '404':
          description: ''
          schema:
            type: object
            properties:
              msg:
                type: string
        '500':
          description: ''
          schema:
            type: object
            properties:
              error:
                type: string
definitions:
  date:
    type: object
    properties:
      accURl:
        type: string
      transportUrl:
        type: string
      date:
        type: string
